/* This file will hold helper methods for this package


   Temporary use of this file is to reference inspirations:

 - https://gitter.im/metacurrency/holochain?at=58c92679de5049082293900f (Metacurrency's Ceptr as a branch of distributed computing, 
   									 where data is validatable without global consensus on publicly stored data
								       - subproject 'holochain') 

 - http://prijazni-sovraznik.si (Project of a diverging team, on topic of "japanese knotweed", an invasive plant with a rhizomatic root structure) */

// eventSchema is generated by selecting "actions" definitions and "agent" types (as defined within scope of application)

const eventSchema = function(actionsArray, agentTypesArray){

  var schemaArray = {};

  for(var action in actionsArray) {
   if(actionsArray.hasOwnProperty(action)) {

    var enacted = (actionsArray[action].substr(0,1) == '+') : action + actionsArray[action].substr(1) : actionsArray[action];

  	for(var agentType in agentTypesArray) {
   	 if(actionsArray.hasOwnProperty(action)) {
      schemaArray[enacted+ "_by_"+agentType] = Integer;
     }
    }

    schemaArray['timestamp_'+enacted] = Integer;
   }
  }

  return schemaArray;
}
