

// The beginning of this file should actually be generated by parsing README.md (providing default initiation constant) - by a documentation-first paradigm

import { 
  nodeState_gql 
} from './db.augmentation.types'


import { generateResponder } from './db.generator'

export default function rhizomeInit(
  augmentationNamespace
){

  // Check if Sql schema exists as declared
  // >> generate tables otherwise

  return {
    // compiled API interface (gql-ready)
  }
}