// actionSchema is generated by selecting "actions" definitions (as defined within scope of application)

const actionSchema = function(actionsArray, agentType, render = false){ // agentId is unified (service+"-"+entityType+"_"+id); isn't 'user_id' or 'circle_id'

  var schemaArray = {};

  for(var action in actionsArray) {
   if(actionsArray.hasOwnProperty(action)) {

    var enacted = (actionsArray[action].substr(0,1) == '+') : action + actionsArray[action].substr(1) : actionsArray[action];

    schemaArray[enacted+ "_by_"+agentType]] = String;
    schemaArray['timestamp_'+enacted] = Integer;
   }
  }

  return (render) ? parseSchema(schemaArray) : schemaArray;
}